### ISSUE TITLE
Can I build iOS version?

### ISSUE THREAD

**Issue by Calvin-Huang** [erttyy8821/MyDiary#1]
This work is pretty interesting.
Can I join this project?

**Comment by michael34435** [comment]
Same here

**Comment by erttyy8821** [comment]
It's Okay, but I don't have any mac & iOS devices for checking project  now,
So I think that  you can follow my use case & APK to create a new repository !
If you do it , I will write a UI flow , then we can check specification from it :)

**Comment by Calvin-Huang** [comment]
Here is the repo: https://github.com/Calvin-Huang/MyDiary
I will start to construct to app tonight!

Thank you! 😆
